### ISSUE TITLE
Archiving OpenJ9 how-to

### ISSUE THREAD

**Issue by tsegismont** [vertx-howtos/openj9-howto#2]
Given OpenJ9 builds are [no longer available](https://eclipse.dev/openj9/docs/builds/) in the community, this how-to may is not much relevant anymore.

cc @vietj @jponge

**Comment by jponge** [comment]
Agreed.

I suggest we add a warning / notice at the top of the howto rather than
removing it, WDYT?

**Comment by tsegismont** [comment]
Or we point users to Semeru Runtimes
